# Generated by Django 4.2.2 on 2023-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('mail', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
    ]
